name: License Check

on:
  pull_request:
    paths:
      - '**.target'

jobs:
  check-dash-licenses:
    uses: eclipse-dash/dash-licenses/.github/workflows/mavenLicenseCheck.yml@268cabe5d46d65efd64ff5eee0b9cb2b0e36f89e # 1.1.0
    with:
      projectId: tools.windowbuilder
