name: License Check

on:
  pull_request:
    paths:
      - '**.target'

jobs:
  check-dash-licenses:
    uses: eclipse-dash/dash-licenses/.github/workflows/mavenLicenseCheck.yml@ade01c63e5f8c32699afd23d608209cf5864dc1f # 1.1.0
    with:
      projectId: tools.windowbuilder
